app = "hael-server"
primary_region = "ams"

[build]
  dockerfile = "packages/server/Dockerfile"

[env]
  PORT = "3000"
  HOST = "0.0.0.0"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
